    # .platform.app.yaml

    name: 'astroSurf'
    type: 'python:3.10'

    # The relationships of the application with services.
    relationships:
        database: 'db:postgresql'

    # The build-time dependencies of the application.
    build:
        flavor: 'pip'
        commands:
            - 'pip install -r requirements.txt'

    # The size of the persistent disk of the application (in MB).
    disk: 2048

    # The web-accessible directory of the application, relative to its root.
    web:
        commands:
            start: 'gunicorn astro_project.wsgi:application --log-file -'
        upstream:
            socket_family: 'unix'
        locations:
            '/':
                passthru: true
            '/static':
                root: 'staticfiles'
                expires: 1h
                allow: true

    # Mounts for persistent storage.
    mounts:
        'static':
            source: 'local'
            source_path: 'static'

    # Hooks that will be run at different points in the deployment process.
    hooks:
        build: |
            set -e
            python manage.py collectstatic --noinput
        deploy: |
            set -e
            python manage.py migrate --noinput
